version: '3'
services:
  app:
    # image: microstudi/decidim-hacks:latest
    build: .
    # container_name: decidim-hacks
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
    ports:
      - 3000:3000
      - 3035:3035
      - 3035:3035/udp
    links:
      - pg
    restart: "no"
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  openvscode-server:
    image: "gitpod/openvscode-server"
    volumes:
     - .:/home/workspace:cached
    environment:
      - VSCODE_PLUGINS='ruby-on-rails,autocomplete-ruby'
    ports:
      - 8080:3000
volumes:
  bundle: {}
  pg-data: {}
